version: '2'
services:
    plex:
        container_name: plex
        build: .
        privileged: true
        restart: always
        volumes:
            - ./config/plex:/config
            - ./media:/data
            - ./rclone.conf:/rclone.conf
            - ./:/btplex
        dns:
            - 8.8.8.8
            - 8.8.4.4
        env_file: config.env
        environment:
            - SKIP_CHOWN_CONFIG=TRUE
            - http_proxy=
            - https_proxy=
    radarr:
        container_name: radarr
        image: linuxserver/radarr
        restart: always
        volumes:
            - ./config/radarr:/config
            - ./media/downloads:/downloads
            - ./media/movies:/movies
        dns:
            - 8.8.8.8
            - 8.8.4.4
        links:
            - jackett
            - transmission
        environment:
            - PUID=0
            - PGID=0
    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        restart: always
        volumes:
            - ./config/sonarr:/config
            - ./media/downloads:/downloads
            - ./media/tvshows:/tv
        dns:
            - 8.8.8.8
            - 8.8.4.4
        links: 
            - jackett
            - transmission
        environment:
            - PUID=0
            - PGID=0
    jackett:
        container_name: jackett
        image: linuxserver/jackett
        restart: always
        volumes:
            - ./config:/config
            - ./media/downloads:/downloads
        env_file: config.env
    transmission:
        container_name: transmission
        image: haugene/transmission-openvpn
        privileged: true
        restart: always
        volumes:
            - ./config/transmission:/config
            - ./media:/data
        dns:
            - 8.8.8.8
            - 8.8.4.4
        env_file: config.env
        environment:
            - OPENVPN_OPTS=--mute-replay-warnings 
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_USERNAME=btuser 
            - TRANSMISSION_RPC_PASSWORD=btpass
            - TRANSMISSION_DOWNLOAD_DIR=/data/downloads
            - TRANSMISSION_INCOMPLETE_DIR=/data/downloads
            - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
            - TRANSMISSION_HOME=/config/transmission-home
            - TRANSMISSION_IDLE_SEEDING_LIMIT=5
            - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
            - TRANSMISSION_PREALLOCATION=0
            - TRANSMISSION_RATIO_LIMIT=2
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_SEED_QUEUE_ENABLED=true
            - TRANSMISSION_SEED_QUEUE_SIZE=2
            - TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=3
    caddy:
        container_name: caddy
        image: abiosoft/caddy
        restart: always
        volumes:
            - ./config/caddy/Caddyfile:/etc/Caddyfile
            - ./config/caddy:/root/.caddy
        ports:
            - 443:443
            - 32400:32400
            - 8787:8787
            - 9898:9898
            - 9117:9117
            - 9091:9091
        links:
            - plex
            - radarr
            - sonarr
            - jackett
            - transmission
        env_file: config.env
        environment:
            - http_proxy=
            - https_proxy=
