version: '2'
services:
    plex:
        container_name: plex
        build: .
        privileged: true
        restart: always
        volumes:
            - ./config/plex:/config
            - ./media:/data
        dns:
            - 8.8.8.8
            - 8.8.4.4
        ports:
            - 32400:32400
        environment:
            - SKIP_CHOWN_CONFIG=TRUE
        env_file: .env
    radarr:
        container_name: radarr
        image: linuxserver/radarr
        restart: always
        volumes:
            - ./config/radarr:/config
            - ./media/downloads:/downloads
            - ./media/movies:/movies
        dns:
            - 8.8.8.8
            - 8.8.4.4
        links:
            - transmission
        environment:
            - PUID=0
            - PGID=0
    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        restart: always
        volumes:
            - ./config/sonarr:/config
            - ./media/downloads:/downloads
            - ./media/tvshows:/tv
        dns:
            - 8.8.8.8
            - 8.8.4.4
        links: 
            - transmission
        environment:
            - PUID=0
            - PGID=0
    transmission:
        container_name: transmission
        image: haugene/transmission-openvpn
        privileged: true
        restart: always
        volumes:
            - ./config/transmission:/config
            - ./media:/data
        dns:
            - 8.8.8.8
            - 8.8.4.4
        environment:
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings 
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_USERNAME=btuser 
            - TRANSMISSION_RPC_PASSWORD=btpass
            - TRANSMISSION_DOWNLOAD_DIR=/data/downloads
            - TRANSMISSION_INCOMPLETE_DIR=/data/downloads
            - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
            - TRANSMISSION_HOME=/config/transmission-home
            - TRANSMISSION_IDLE_SEEDING_LIMIT=5
            - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
            - TRANSMISSION_PREALLOCATION=0
            - TRANSMISSION_RATIO_LIMIT=2
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_SEED_QUEUE_ENABLED=true
            - TRANSMISSION_SEED_QUEUE_SIZE=2
            - TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=3
        env_file: .env
    caddy:
        container_name: caddy
        image: abiosoft/caddy
        volumes:
            - ./config/caddy/Caddyfile:/etc/Caddyfile
            - ./config/caddy:/root/.caddy
        ports:
            - 8787:8787
            - 9898:9898
            - 9091:9091
        links:
            - radarr
            - sonarr
            - transmission
